// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "de42c9fe-09f1-4c4d-aa56-05754c16916c";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onH20CurrentPercentageChange();
void onH20TotTimeChange();
void onTimeUseChange();

int h20_CurrentPercentage;
CloudTime h20_totTime;
CloudTime time_Use;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(h20_CurrentPercentage, READWRITE, 500 * SECONDS, onH20CurrentPercentageChange);
  ArduinoCloud.addProperty(h20_totTime, READWRITE, 500 * SECONDS, onH20TotTimeChange);
  ArduinoCloud.addProperty(time_Use, READWRITE, 500 * SECONDS, onTimeUseChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
